import React from 'react';

const PrivacyPolicy: React.FC = () => {
  return (
    <div
  style={{
    maxWidth: "800px",
    margin: "0 auto",
    marginTop: "90px",
    padding: "30px",
    paddingTop: "80px",
    fontFamily: "Arial, sans-serif",
    color: "#333",
    lineHeight: 1.6,
    backgroundColor: "#f8f9fa",
    borderRadius:'12px',
  }}
>
      <h1 style={{ textAlign: 'center', color: '#333' }}>Privacy Policy</h1>
      <p style={{ color: '#444', margin: '10px 0' }}>
        <strong>Last updated:</strong> March 09, 2025
      </p>

      <section>
        <p style={{ color: '#444', margin: '10px 0' }}>
          This Privacy Policy describes Our policies and procedures on the collection, use and disclosure of Your information when You use the Service and tells You about Your privacy rights and how the law protects You.
        </p>
        <p style={{ color: '#444', margin: '10px 0' }}>
          We use Your Personal data to provide and improve the Service. By using the Service, You agree to the collection and use of information in accordance with this Privacy Policy.
          
        </p>
      </section>

      <section>
        <h2 style={{ color: '#555', marginTop: '20px' }}>Interpretation and Definitions</h2>
        <h3 style={{ color: '#666', marginTop: '15px' }}>Interpretation</h3>
        <p style={{ color: '#444', margin: '10px 0' }}>
          The words of which the initial letter is capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or in plural.
        </p>

        <h3 style={{ color: '#666', marginTop: '15px' }}>Definitions</h3>
        <p style={{ color: '#444', margin: '10px 0' }}>For the purposes of this Privacy Policy:</p>
        <ul style={{ margin: '10px 0', paddingLeft: '20px' }}>
          <li style={{ margin: '5px 0' }}>
            <strong>Account</strong> means a unique account created for You to access our Service or parts of our Service.
          </li>
          <li style={{ margin: '5px 0' }}>
            <strong>Affiliate</strong> means an entity that controls, is controlled by or is under common control with a party, where "control" means ownership of 50% or more of the shares, equity interest or other securities entitled to vote for election of directors or other managing authority.
          </li>
          <li style={{ margin: '5px 0' }}>
            <strong>Company</strong> (referred to as either "the Company", "We", "Us" or "Our" in this Agreement) refers to HappyPet LLC, Colombo 04.
          </li>
          <li style={{ margin: '5px 0' }}>
            <strong>Cookies</strong> are small files that are placed on Your computer, mobile device or any other device by a website, containing the details of Your browsing history on that website among its many uses.
          </li>
          <li style={{ margin: '5px 0' }}>
            <strong>Country</strong> refers to: Sri Lanka
          </li>
          <li style={{ margin: '5px 0' }}>
            <strong>Device</strong> means any device that can access the Service such as a computer, a cellphone or a digital tablet.
          </li>
          <li style={{ margin: '5px 0' }}>
            <strong>Personal Data</strong> is any information that relates to an identified or identifiable individual.
          </li>
          <li style={{ margin: '5px 0' }}>
            <strong>Service</strong> refers to the Website.
          </li>
          <li style={{ margin: '5px 0' }}>
            <strong>Service Provider</strong> means any natural or legal person who processes the data on behalf of the Company. It refers to third-party companies or individuals employed by the Company to facilitate the Service, to provide the Service on behalf of the Company, to perform services related to the Service or to assist the Company in analyzing how the Service is used.
          </li>
          <li style={{ margin: '5px 0' }}>
            <strong>Usage Data</strong> refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit).
          </li>
          <li style={{ margin: '5px 0' }}>
            <strong>Website</strong> refers to Happy Pet, accessible from{' '}
            <a
              href="happypet.com.lk"
              rel="external nofollow noopener"
              target="_blank"
              style={{ color: '#007bff', textDecoration: 'none' }}
            >
              happypet.com.lk
            </a>
          </li>
          <li style={{ margin: '5px 0' }}>
            <strong>You</strong> means the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable.
          </li>
        </ul>
      </section>

      {/* Add other sections similarly */}

      <section>
        <h2 style={{ color: '#555', marginTop: '20px' }}>Contact Us</h2>
        <p style={{ color: '#444', margin: '10px 0' }}>
          If you have any questions about this Privacy Policy, You can contact us:
        </p>
        <ul style={{ margin: '10px 0', paddingLeft: '20px' }}>
          <li style={{ margin: '5px 0' }}>By email: happypetlk.com@gmail.com</li>
          <li style={{ margin: '5px 0' }}>
            By visiting this page on our website:{' '}
            <a
              href="happypet.com.lk"
              rel="external nofollow noopener"
              target="_blank"
              style={{ color: '#007bff', textDecoration: 'none' }}
            >
              happypet.com.lk
            </a>
          </li>
          <li style={{ margin: '5px 0' }}>By phone number: +94770092167</li>
        </ul>
      </section>
    </div>
  );
};

export default PrivacyPolicy;